version: '3'

services:
  app:
    build: .
    command: npm run start:app
    depends_on:
      - elasticsearch
      - mariadb
      - redis
      - zenko
    environment:
      AWS_ACCESS_KEY_ID: accessKey1
      AWS_SECRET_ACCESS_KEY: verySecretKey1
      AWS_ENDPOINT: http://zenko:8000
      AWS_DEFAULT_REGION: us-east-1
      DATABASE_URL: mysql://app:app@mariadb:3306/app
      DEBUG: starter-nodejs:*
      ELASTICSEARCH_URL: http://elasticsearch:9200
      JWT_SECRET: not_very_secret
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
    healthcheck:
      test: curl -f http://localhost:3000
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules

  elasticsearch:
    image: elasticsearch:7.14.0
    environment:
      ES_JAVA_OPTS: '-Xmx512m -Xms512m'
      discovery.type: single-node
    ports:
      - '9200:9200'
      - '9300:9300'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_USER: app
      PMA_PASSWORD: app
    ports:
      - '9000:80'

  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  queue:
    build: .
    command: npm run start:queue
    depends_on:
      - elasticsearch
      - mariadb
      - redis
      - zenko
    environment:
      AWS_ACCESS_KEY_ID: accessKey1
      AWS_SECRET_ACCESS_KEY: verySecretKey1
      AWS_ENDPOINT: http://zenko:8000
      AWS_DEFAULT_REGION: us-east-1
      DATABASE_URL: mysql://app:app@mariadb:3306/app
      DEBUG: starter-nodejs:*
      ELASTICSEARCH_URL: http://elasticsearch:9200
      JWT_SECRET: not_very_secret
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/app
      - /app/node_modules

  zenko:
    image: zenko/cloudserver
    environment:
      ENDPOINT: zenko
      REMOTE_MANAGEMENT_DISABLE: '1'
      S3DATAPATH: /data
      S3METADATAPATH: /metadata
    ports:
      - '8000:8000'
    volumes:
      - zenko_data:/data
      - zenko_metadata:/metadata

volumes:
  elasticsearch_data:
  mariadb_data:
  redis_data:
  zenko_data:
  zenko_metadata:
