version: '3'

services:
  app:
    build: .
    command: npm run start:app
    depends_on:
      - elasticsearch
      - mailhog
      - mariadb
      - minio
      - redis
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: not_very_secret
      AWS_ENDPOINT: http://minio:9000
      AWS_DEFAULT_REGION: us-east-1
      DATABASE_URL: mysql://app:app@mariadb:3306/app
      DEBUG: starter-nodejs:*
      ELASTICSEARCH_URL: http://elasticsearch:9200
      JWT_SECRET: not_very_secret
      MAILER_URL: smtp://mailhog:1025
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
    healthcheck:
      test: curl -f http://localhost:3000
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules

  elasticsearch:
    image: elasticsearch:7.14.0
    environment:
      ES_JAVA_OPTS: '-Xmx512m -Xms512m'
      discovery.type: single-node
    ports:
      - '9200:9200'
      - '9300:9300'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '1025:1025'
      - '8025:8025'

  mariadb:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql

  minio:
    image: minio/minio:latest
    command: minio server /data/minio --console-address ":8900"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: not_very_secret
    ports:
      - '9000:9000'
      - '8900:8900'
    volumes:
      - minio_data:/data/minio

  phpmyadmin:
    image: phpmyadmin:5
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_USER: app
      PMA_PASSWORD: app
    ports:
      - '8000:80'

  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  schedule:
    build: .
    command: npm run start:schedule
    depends_on:
      - elasticsearch
      - mailhog
      - mariadb
      - minio
      - redis
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: not_very_secret
      AWS_ENDPOINT: http://minio:9000
      AWS_DEFAULT_REGION: us-east-1
      DATABASE_URL: mysql://app:app@mariadb:3306/app
      DEBUG: starter-nodejs:*
      ELASTICSEARCH_URL: http://elasticsearch:9200
      JWT_SECRET: not_very_secret
      MAILER_URL: smtp://mailhog:1025
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      SKIP_MIGRATIONS: 'true'
    volumes:
      - .:/app
      - /app/node_modules

  worker:
    build: .
    command: npm run start:worker
    depends_on:
      - elasticsearch
      - mailhog
      - mariadb
      - minio
      - redis
    environment:
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: not_very_secret
      AWS_ENDPOINT: http://minio:9000
      AWS_DEFAULT_REGION: us-east-1
      DATABASE_URL: mysql://app:app@mariadb:3306/app
      DEBUG: starter-nodejs:*
      ELASTICSEARCH_URL: http://elasticsearch:9200
      JWT_SECRET: not_very_secret
      MAILER_URL: smtp://mailhog:1025
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      SKIP_MIGRATIONS: 'true'
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  elasticsearch_data:
  mariadb_data:
  minio_data:
  redis_data:
